motor_1_setpoint:
  type: std_msgs/Float32
  throttle:
    min: -1
    max: 1
    to: data
    default: 0

motor_2_setpoint:
  type: std_msgs/Float32
  throttle:
    min: -1
    max: 1
    to: data
    default: 0